using DG.Tweening;
using System.Collections;
using UnityEngine;
using UnityEngine.SceneManagement;

// mostly generated by Google Gemini 3 Pro (we runnin low on time sory)
// checked and revised by andy
// does cool thingy to transition into/out of battle
public class TransitionManager : MonoBehaviour
{
    public static TransitionManager Instance;

    [Header("References")]
    [SerializeField] CanvasGroup transitionCanvasGroup;
    [SerializeField] CanvasGroup pauseMenuGroup; // to disable interactions
    [SerializeField] RectTransform leftPanel;
    [SerializeField] RectTransform rightPanel;

    [Header("Settings")]
    // scenes that have their own custom intro animations (like waterfall)
    // so we shouldn't mess with them
    [SerializeField] string[] ignoreIntroScenes = new string[] { "MainMenu" };

    private void Awake()
    {
        if (Instance != null && Instance != this)
        {
            Destroy(gameObject);
        }
        else
        {
            Instance = this;
            DontDestroyOnLoad(gameObject);
        }
    }

    private void OnEnable()
    {
        SceneManager.sceneLoaded += OnSceneLoaded;
    }

    private void OnDisable()
    {
        SceneManager.sceneLoaded -= OnSceneLoaded;
    }

    // runs automatically every time a scene loads
    private void OnSceneLoaded(Scene scene, LoadSceneMode mode)
    {
        foreach (string ignoredScene in ignoreIntroScenes)
        {
            if (scene.name == ignoredScene)
            {
                ResetState(forceTransparent: true);
                return;
            }
        }

        StartCoroutine(AnimateIn());
    }

    public void TransitionTo(string sceneName)
    {
        StartCoroutine(TransitionRoutine(sceneName));
    }


    private void ResetState(bool forceTransparent)
    {
        if (transitionCanvasGroup != null)
        {
            transitionCanvasGroup.blocksRaycasts = false;
            transitionCanvasGroup.alpha = forceTransparent ? 0 : 1;
        }
    }

    IEnumerator TransitionRoutine(string sceneName)
    {
        transitionCanvasGroup.blocksRaycasts = true;
        yield return StartCoroutine(AnimateOut());

        SceneLoader.Load(sceneName);
    }

    IEnumerator AnimateOut()
    {
        pauseMenuGroup.interactable = false;

        Sequence sequence = DOTween.Sequence();

        sequence.Append(leftPanel.DOMoveX(100, 0.5f).SetEase(Ease.OutQuart).SetUpdate(true));
        sequence.Join(rightPanel.DOMoveX(1100, 0.5f).SetEase(Ease.OutQuart).SetUpdate(true));

        yield return sequence.WaitForCompletion();
    }

    IEnumerator AnimateIn()
    {
        transitionCanvasGroup.blocksRaycasts = true;

        Sequence sequence = DOTween.Sequence();

        sequence.Append(leftPanel.DOMoveX(-700, 0.5f).SetEase(Ease.InQuart).SetUpdate(true));
        sequence.Join(rightPanel.DOMoveX(1900, 0.5f).SetEase(Ease.InQuart).SetUpdate(true));

        yield return sequence.WaitForCompletion();

        transitionCanvasGroup.blocksRaycasts = false;
    }
}