using DG.Tweening;
using System.Collections;
using UnityEngine;
using UnityEngine.SceneManagement;

// mostly generated by Google Gemini 3 Pro (we runnin low on time sory)
// checked and revised by andy
// does cool thingy to transition into/out of battle
public class TransitionManager : MonoBehaviour
{
    public static TransitionManager Instance;

    [Header("References")]
    [SerializeField] CanvasGroup transitionCanvasGroup;
    [SerializeField] RectTransform transitionElement;

    [Header("Settings")]
    // scenes that have their own custom intro animations (like waterfall)
    // so we shouldn't mess with them
    [SerializeField] string[] ignoreIntroScenes = new string[] { "MainMenu" };

    private void Awake()
    {
        if (Instance != null && Instance != this)
        {
            Destroy(gameObject);
        }
        else
        {
            Instance = this;
            DontDestroyOnLoad(gameObject);
        }
    }

    private void OnEnable()
    {
        SceneManager.sceneLoaded += OnSceneLoaded;
    }

    private void OnDisable()
    {
        SceneManager.sceneLoaded -= OnSceneLoaded;
    }

    // runs automatically every time a scene loads
    private void OnSceneLoaded(Scene scene, LoadSceneMode mode)
    {
        foreach (string ignoredScene in ignoreIntroScenes)
        {
            if (scene.name == ignoredScene)
            {
                ResetState(forceTransparent: true);
                return;
            }
        }

        // otherwise, start the scene covered and fade in
        StartCoroutine(AnimateIn());
    }

    public void TransitionTo(string sceneName)
    {
        StartCoroutine(TransitionRoutine(sceneName));
    }

    // helper to reset the canvas
    private void ResetState(bool forceTransparent)
    {
        if (transitionCanvasGroup != null)
        {
            transitionCanvasGroup.blocksRaycasts = false;
            transitionCanvasGroup.alpha = forceTransparent ? 0 : 1;
        }
    }

    IEnumerator TransitionRoutine(string sceneName)
    {
        // 1. ANIMATE OUT (Cover Screen)
        transitionCanvasGroup.blocksRaycasts = true;
        yield return StartCoroutine(AnimateOut());

        // 2. LOAD SCENE
        // call the fake loader we made earlier
        SceneLoader.Load(sceneName);

        // note: we don't need to call AnimateIn() here anymore
        // because OnSceneLoaded will trigger automatically when the new scene arrives
    }

    // vvvvv FILL IN UR TWEENS vvvvv

    IEnumerator AnimateOut()
    {
        // this is "Closing the curtain" (Exiting the old scene)

        transitionCanvasGroup.alpha = 0;

        // example: fade to black
        yield return transitionCanvasGroup.DOFade(1, 0.5f).SetUpdate(true).WaitForCompletion();

    }

    IEnumerator AnimateIn()
    {

        transitionCanvasGroup.alpha = 1;
        transitionCanvasGroup.blocksRaycasts = true;

        // example: fade to clear
        yield return transitionCanvasGroup.DOFade(0, 0.5f).SetEase(Ease.InQuad).SetUpdate(true).WaitForCompletion();

        transitionCanvasGroup.blocksRaycasts = false;
    }
}