using Shrimp5.UIContract;
using UnityEngine;

// generated by chatgpt to test ui battle model
namespace Shrimp5.Mock
{
    public class BattleUITestHarness : MonoBehaviour
    {
        private MockBattleModel _model;
        private MockBattleController _controller;

        // UI owns selection
        private int _selectedIndex = 0;

        private void Start()
        {
            _model = new MockBattleModel();
            _controller = new MockBattleController(_model);

            _model.Changed += OnModelChanged;
            OnModelChanged();
        }

        private void OnDestroy()
        {
            if (_model != null) _model.Changed -= OnModelChanged;
        }

        private void Update()
        {
            var snap = _model.GetSnapshot();
            int count = snap.moves?.Count ?? 0;
            if (count <= 0) return;

            // horizontal only
            if (Input.GetKeyDown(KeyCode.LeftArrow)) SetSelected(_selectedIndex - 1, count);
            if (Input.GetKeyDown(KeyCode.RightArrow)) SetSelected(_selectedIndex + 1, count);

            // Z confirm, C inspect, X back
            if (Input.GetKeyDown(KeyCode.Z)) _controller.Confirm(_selectedIndex);
            if (Input.GetKeyDown(KeyCode.C)) _controller.Inspect(_selectedIndex);
            if (Input.GetKeyDown(KeyCode.X)) _controller.Back();

            // optional pause
            if (Input.GetKeyDown(KeyCode.Escape)) _controller.PauseToggle();
        }

        private void SetSelected(int next, int count)
        {
            // wrap feels good undertale-style
            if (next < 0) next = count - 1;
            if (next >= count) next = 0;

            _selectedIndex = next;

            // tooltip: focus == "hover"
            _controller.SetTooltipTarget($"command.{_selectedIndex}");

            // if you want the model to mirror selection (since snapshot has selectedIndex)
            var snap = _model.GetSnapshot();
            snap.selectedIndex = _selectedIndex;
            _model.SetSnapshot(snap);
        }

        private void OnModelChanged()
        {
            var snap = _model.GetSnapshot();
            var events = _model.DrainUIEvents();

            Debug.Log($"[MOCK UI] mode={snap.battleMode} prompt='{snap.promptText}' selected={_selectedIndex} cmds={snap.moves?.Count}");

            if (snap.tooltipData.isVisible)
                Debug.Log($"[TOOLTIP] {snap.tooltipData.title}: {snap.tooltipData.body}");

            foreach (var e in events)
                Debug.Log($"[EVENT] {e.eventType} target={e.target} old={e.oldValue} new={e.newValue}");
        }
    }
}
