using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Shrimp5.UIContract;

// generated by google gemini 3 pro. unchecked
// used to test stuff.
public class BattleUITester : MonoBehaviour, IBattleUIActions
{
    [Header("Refs")]
    public BattleUIModel model;

    // Internal flags to handle the dialogue wait logic
    private bool _wantsToAdvance = false;
    private bool _wantsToSkipAll = false;

    // --- INTERFACE IMPLEMENTATION (So Input Script thinks we are the game) ---

    public void Confirm(int index)
    {
        // Start the fake turn sequence when player picks a move
        StartCoroutine(TestTurnSequence(index));
    }

    public void DialogueConfirm() => _wantsToAdvance = true;
    public void DialogueSkipAll() => _wantsToSkipAll = true;

    // NEW: Handle Tooltips!
    public void SetTooltipTarget(string content)
    {
        var snap = model.GetSnapshot();

        if (string.IsNullOrEmpty(content))
        {
            snap.tooltipData.isVisible = false;
        }
        else
        {
            snap.tooltipData.isVisible = true;
            snap.tooltipData.text = content;
        }

        model.SetSnapshot(snap);
    }

    // Empty stubs for stuff we don't need to test right now
    public void Back() { }
    public void Secondary(int index) { }
    public void PauseToggle() { }


    // --- THE TEST SEQUENCES ---

    [ContextMenu("Reset Test State")]
    public void ResetState()
    {
        var snap = new BattleSnapshot();
        snap.battleMode = BattleUIMode.ChoosingAction;
        snap.promptText = "Test Ready. Hover icons or Pick a move.";

        // 1. Setup Moves
        snap.moves = new List<MoveData>
        {
            new MoveData { moveName = "Slap", iconID = "attack_basic", moveShortDescription = "Basic slap.", isEnabled = true },
            new MoveData { moveName = "Big Pinch", iconID = "attack_claw", moveShortDescription = "Deals big dmg.", isEnabled = true },
            new MoveData { moveName = "Heal", iconID = "item_potion", moveShortDescription = "Drink soup.", isEnabled = true },
            new MoveData { moveName = "Switch", iconID = "icon_switch", moveShortDescription = "Run away.", isEnabled = true }
        };

        // 2. Setup Player (With Status Icons!)
        snap.playerInfoData = new HudData
        {
            teammateName = "Test Shrimp",
            hp = 100,
            maxHp = 100,
            portraitIconID = "shrimp_happy",

            // The double-list: [ [ID, Desc], [ID, Desc] ]
            passives = new List<List<string>>
            {
                new List<string> { "icon_poison", "Poison: Taking 5 DMG per turn." },
                new List<string> { "icon_strength", "Strength: ATK is boosted by 50%!" }
            }
        };

        // 3. Setup Enemy
        snap.enemyInfoData = new HudData
        {
            teammateName = "Test Enemy",
            hp = 80,
            maxHp = 80,
            portraitIconID = "crab_angry",
            passives = new List<List<string>>() // empty list
        };

        // 4. Reset Tooltip
        snap.tooltipData = new TooltipData { isVisible = false };

        model.SetSnapshot(snap);
        Debug.Log("Reset Complete.");
    }

    // The Turn Logic Simulation
    private IEnumerator TestTurnSequence(int moveIndex)
    {
        Debug.Log("Starting Test Turn...");
        var snapshot = model.GetSnapshot();

        // Lock UI
        snapshot.battleMode = BattleUIMode.ResolvingAction;
        snapshot.flavorText = "";
        _wantsToSkipAll = false;
        model.SetSnapshot(snapshot);

        // Text 1
        yield return RunDialogueStep("Shrimp used a Move!");
        if (_wantsToSkipAll) goto EndSequence;

        // Text 2 + Damage
        snapshot.enemyInfoData.hp -= 20;
        yield return RunDialogueStep("It hit very hard!");
        if (_wantsToSkipAll) goto EndSequence;

        // End
        EndSequence:
        snapshot.battleMode = BattleUIMode.ChoosingAction;
        snapshot.promptText = "Your move again.";
        snapshot.flavorText = "";

        // Reset flags
        _wantsToAdvance = false;
        _wantsToSkipAll = false;

        model.SetSnapshot(snapshot);
    }

    private IEnumerator RunDialogueStep(string text)
    {
        _wantsToAdvance = false;
        var snap = model.GetSnapshot();
        snap.flavorText = text;
        model.SetSnapshot(snap);

        // wait for Z or C
        yield return new WaitUntil(() => _wantsToAdvance || _wantsToSkipAll);
    }
}