using UnityEngine;
using System.Collections.Generic;
using Shrimp5.UIContract;


// generated by Google Gemini 3 Pro; not checked/revised yet
public class BattleUITester : MonoBehaviour
{
    // drag your model here
    public BattleUIModel model;

    // helper to make dummy data less painful to write
    MoveData CreateMove(string name, string icon, string desc, bool enabled = true)
    {
        return new MoveData
        {
            moveName = name,
            iconID = icon,
            moveShortDescription = desc,
            isEnabled = enabled,
            hintText = "Z to Confirm"
        };
    }

    [ContextMenu("Test 1: Standard Player Turn")]
    public void TestStandardTurn()
    {
        var snapshot = new BattleSnapshot();
        snapshot.battleMode = BattleUIMode.ChoosingAction;
        snapshot.promptText = "What will Shrimp do?";
        snapshot.selectedIndex = 0; // highlighting first move

        // create the standard 3 moves + 1 switch
        snapshot.moves = new List<MoveData>
        {
            CreateMove("Bubble Beam", "attack_bubble", "Deals 20 DMG. Wet."),
            CreateMove("Claw Snap", "attack_claw", "Deals 15 DMG. Ow."),
            CreateMove("Heal Up", "item_potion", "Restores 50 HP."),
            CreateMove("Switch", "icon_switch", "Swap teammate.") // the switch button
        };

        // we need dummy data for players too so the top bars don't crash
        snapshot.playerInfoData = new HudData { teammateName = "Cool Shrimp", hp = 100, maxHp = 100, portraitIconID = "shrimp_happy" };
        snapshot.enemyInfoData = new HudData { teammateName = "Evil Crab", hp = 80, maxHp = 80, portraitIconID = "crab_angry" };

        snapshot.tooltipData = new TooltipData { isVisible = false };

        model.SetSnapshot(snapshot);
        Debug.Log("Test 1 Sent!");
    }

    [ContextMenu("Test 2: Cursor Moved to Slot 2")]
    public void TestCursorMove()
    {
        // get the current snapshot so we don't have to rewrite everything
        var snapshot = model.GetSnapshot();

        // just change the index
        snapshot.selectedIndex = 1; // 0 is first, 1 is second

        model.SetSnapshot(snapshot);
        Debug.Log("Test 2 Sent (Cursor Moved)!");
    }

    [ContextMenu("Test 3: Move Disabled (Out of PP)")]
    public void TestDisabledMove()
    {
        var snapshot = model.GetSnapshot();

        // let's disable the 3rd move (index 2)
        var move = snapshot.moves[2];
        move.isEnabled = false;
        move.moveName = "Heal Up (0 PP)";
        snapshot.moves[2] = move;

        model.SetSnapshot(snapshot);
        Debug.Log("Test 3 Sent (Move Disabled)!");
    }

    [ContextMenu("Test 4: Weird Edge Case (Only 2 Moves)")]
    public void TestWeirdLayout()
    {
        var snapshot = model.GetSnapshot();

        // what if a pokemon only has 2 moves?
        // this tests if your object pooling correctly hides the unused buttons
        snapshot.moves = new List<MoveData>
        {
            CreateMove("Struggle", "attack_basic", "Deals 1 DMG."),
            CreateMove("Switch", "icon_switch", "Swap teammate.")
        };

        snapshot.selectedIndex = 0;

        model.SetSnapshot(snapshot);
        Debug.Log("Test 4 Sent (2 Moves Only)!");
    }
}