using System;
using Shrimp5.UIContract;


// generated by chatgpt to test ui battle model
namespace Shrimp5.Mock
{
    public class MockBattleController : IBattleUIActions
    {
        private readonly MockBattleModel _model;

        // remember which move we inspected from ChoosingAction (0..2)
        private int _lastInspectedMove = 0;

        public MockBattleController(MockBattleModel model)
        {
            _model = model;
        }

        public void Confirm(int index)
        {
            var snap = _model.GetSnapshot();

            switch (snap.battleMode)
            {
                case BattleUIMode.ChoosingAction:
                    {
                        if (index == 3)
                        {
                            _model.SetSnapshot(MockBattleModel.BuildChoosingSwitch());
                            return;
                        }

                        // pretend damage
                        var next = snap;
                        next.enemyInfoData.hp = Math.Max(0, next.enemyInfoData.hp - 5);
                        next.promptText = "bonk!";
                        _model.SetSnapshot(next);

                        // bounce back (mock)
                        next.promptText = "your move!";
                        _model.SetSnapshot(next);
                        break;
                    }

                case BattleUIMode.ChoosingSwitchTeammate:
                    {
                        // slot 3 is back in our mock list
                        if (index == 3)
                        {
                            _model.SetSnapshot(MockBattleModel.BuildChoosingAction());
                            return;
                        }

                        // pretend switch happened
                        _model.SetPrompt($"switched to slot {index}");
                        _model.SetSnapshot(MockBattleModel.BuildChoosingAction());
                        break;
                    }

                case BattleUIMode.InspectingMove:
                    {
                        // in our inspect snapshot: 0=Back, 1=Use
                        if (index == 0) _model.SetSnapshot(MockBattleModel.BuildChoosingAction());
                        else _model.SetPrompt("used move!");
                        break;
                    }
            }
        }

        public void Inspect(int index)
        {
            var snap = _model.GetSnapshot();

            // Only allow "details" from choosing action on the 3 real moves (0..2)
            if (snap.battleMode == BattleUIMode.ChoosingAction && index >= 0 && index <= 2)
            {
                _lastInspectedMove = index;
                _model.SetSnapshot(MockBattleModel.BuildInspectMove(index));
            }
        }

        public void Back()
        {
            var snap = _model.GetSnapshot();

            if (snap.battleMode == BattleUIMode.ChoosingSwitchTeammate ||
                snap.battleMode == BattleUIMode.InspectingMove)
            {
                _model.SetSnapshot(MockBattleModel.BuildChoosingAction());
            }
        }

        public void PauseToggle()
        {
            var snap = _model.GetSnapshot();
            if (snap.battleMode == BattleUIMode.Paused)
            {
                snap.battleMode = BattleUIMode.ChoosingAction;
                snap.promptText = "your move!";
            }
            else
            {
                snap.battleMode = BattleUIMode.Paused;
                snap.promptText = "paused";
            }
            _model.SetSnapshot(snap);
        }

        public void SetTooltipTarget(string tooltipID)
        {
            // super tiny demo mapping
            // you can make this as fancy as you want later
            var t = new TooltipData { isVisible = true, title = "", body = "" };

            if (string.IsNullOrEmpty(tooltipID))
            {
                t.isVisible = false;
                _model.SetTooltip(t);
                return;
            }

            // examples:
            // "player.stat.attackSpeed"
            // "enemy.status.slow"
            // "command.2"
            switch (tooltipID)
            {
                case "player.stat.attackSpeed":
                    t.title = "attack speed";
                    t.body = "how fast you act. higher usually means you go earlier.";
                    break;

                case "enemy.status.slow":
                    t.title = "slowed";
                    t.body = "attack speed reduced by 6.7 (example).";
                    break;

                default:
                    if (tooltipID.StartsWith("command."))
                    {
                        t.title = "command";
                        t.body = $"tooltip for {tooltipID}";
                    }
                    else
                    {
                        t.isVisible = false;
                    }
                    break;
            }

            _model.SetTooltip(t);
        }
    }
}
