using System;
using System.Collections.Generic;
using Shrimp5.UIContract;

// generated by chatgpt to test the battle ui model
namespace Shrimp5.Mock
{
    public class MockBattleModel : IBattleUIModel
    {
        public event Action Changed;

        private BattleSnapshot _snapshot;
        private readonly List<BattleUIEvent> _events = new();

        public MockBattleModel()
        {
            _snapshot = BuildChoosingAction();
        }

        public BattleSnapshot GetSnapshot() => _snapshot;

        // IMPORTANT: treat this as "drain" semantics (caller should consume once)
        public List<BattleUIEvent> DrainUIEvents()
        {
            var copy = new List<BattleUIEvent>(_events);
            _events.Clear();
            return copy;
        }

        public void SetSnapshot(BattleSnapshot next)
        {
            // tiny hint events (optional)
            if (next.battleMode != _snapshot.battleMode)
                _events.Add(new BattleUIEvent { eventType = BattleUIEventType.ModeChanged, oldValue = (int)_snapshot.battleMode, newValue = (int)next.battleMode });

            if (next.playerInfoData.hp != _snapshot.playerInfoData.hp)
                _events.Add(new BattleUIEvent { eventType = BattleUIEventType.HpChanged, target = "player", oldValue = _snapshot.playerInfoData.hp, newValue = next.playerInfoData.hp });

            if (next.enemyInfoData.hp != _snapshot.enemyInfoData.hp)
                _events.Add(new BattleUIEvent { eventType = BattleUIEventType.HpChanged, target = "enemy", oldValue = _snapshot.enemyInfoData.hp, newValue = next.enemyInfoData.hp });

            _snapshot = next;
            Changed?.Invoke();
        }

        public void SetTooltip(TooltipData tooltip)
        {
            var next = _snapshot;
            next.tooltipData = tooltip;
            _snapshot = next;
            Changed?.Invoke();
        }

        public void SetPrompt(string text)
        {
            var next = _snapshot;
            next.promptText = text;
            _snapshot = next;
            Changed?.Invoke();
        }

        // -------- canned snapshots --------

        public static BattleSnapshot BuildChoosingAction()
        {
            return new BattleSnapshot
            {
                battleMode = BattleUIMode.ChoosingAction,
                promptText = "your move!",
                selectedIndex = 0,

                playerInfoData = new HudData
                {
                    teammateName = "shrimp alpha",
                    hp = 30,
                    maxHp = 40,
                    attack = 8,
                    attackSpeed = 12,
                    portraitIconID = "shrimp_01",
                    statusIconIDs = new List<string> { "buff_atk" }
                },

                enemyInfoData = new HudData
                {
                    teammateName = "evil shrimp",
                    hp = 22,
                    maxHp = 35,
                    attack = 7,
                    attackSpeed = 10,
                    portraitIconID = "shrimp_enemy",
                    statusIconIDs = new List<string> { "slow" }
                },

                moves = new List<MoveData>
                {
                    new MoveData { iconID="move_bite", moveName="Bite", moveShortDescription="DMG 8", isEnabled=true, hintText="Z: select  C: details  X: back" },
                    new MoveData { iconID="move_snack", moveName="Snack", moveShortDescription="HEAL 6", isEnabled=true, hintText="Z: select  C: details  X: back" },
                    new MoveData { iconID="move_slap", moveName="Slap", moveShortDescription="DMG 4 • Stun", isEnabled=true, hintText="Z: select  C: details  X: back" },
                    new MoveData { iconID="ui_switch", moveName="Switch", moveShortDescription="swap shrimp", isEnabled=true, hintText="Z: open  X: back" },
                },

                inspectData = new InspectData { iconID = "", title = "", body = "" },
                tooltipData = new TooltipData { isVisible = false, title = "", body = "" }
            };
        }

        public static BattleSnapshot BuildChoosingSwitch()
        {
            var snap = BuildChoosingAction();
            snap.battleMode = BattleUIMode.ChoosingSwitchTeammate;
            snap.promptText = "pick a shrimp";
            snap.selectedIndex = 0;

            snap.moves = new List<MoveData>
            {
                new MoveData { iconID="shrimp_02", moveName="shrimp beta", moveShortDescription="HP 18/30", isEnabled=true, hintText="Z: switch  X: back" },
                new MoveData { iconID="shrimp_03", moveName="shrimp gamma", moveShortDescription="HP 0/30 (ko)", isEnabled=false, hintText="" },
                new MoveData { iconID="shrimp_04", moveName="shrimp delta", moveShortDescription="HP 12/25", isEnabled=true, hintText="Z: switch  X: back" },
                new MoveData { iconID="ui_back", moveName="Back", moveShortDescription="", isEnabled=true, hintText="Z: back" },
            };

            return snap;
        }

        public static BattleSnapshot BuildInspectMove(int moveIndex)
        {
            var baseSnap = BuildChoosingAction();
            baseSnap.battleMode = BattleUIMode.InspectingMove;
            baseSnap.promptText = "details";
            baseSnap.selectedIndex = 0;

            var move = baseSnap.moves[Math.Clamp(moveIndex, 0, 2)];
            baseSnap.inspectData = new InspectData
            {
                iconID = move.iconID,
                title = move.moveName,
                body = $"longer description for {move.moveName}...\n\nflavor text goes here."
            };

            // you can render buttons separately in UI; this list is just for the bottom row
            baseSnap.moves = new List<MoveData>
            {
                new MoveData { iconID="ui_back", moveName="Back", moveShortDescription="", isEnabled=true, hintText="Z: back" },
                new MoveData { iconID=move.iconID, moveName="Use", moveShortDescription=move.moveName, isEnabled=true, hintText="Z: use  X: back" },
            };

            return baseSnap;
        }
    }
}
