using System.Collections.Generic;
using UnityEngine;

// generated by Google Gemini 3 Pro, checked & revised by andy
// a simple script that converts image ids to actual sprites
public static class SpriteResolver
{
    // dictionary cache
    private static Dictionary<string, Sprite> cache = new Dictionary<string, Sprite>();

    // inside the resources folder
    private const string BASE_PATH = "Art/UI/";

    public static Sprite Get(string spriteID)
    {
        if(string.IsNullOrEmpty(spriteID)) return null;

        // check if it's already there in the dict
        if(cache.ContainsKey(spriteID))
            return cache[spriteID];

        Sprite loadedSprite = Resources.Load<Sprite>(BASE_PATH + spriteID);

        if(loadedSprite != null)
        {
            // save it for next time or whatever
            cache[spriteID] = loadedSprite;
            return loadedSprite;
        }
        else
        {
            // warning
            Debug.LogWarning($"can't find sprite with id: {spriteID} at base path {BASE_PATH}{spriteID}. returning placeholder image instead!");
            return Resources.Load<Sprite>(BASE_PATH + "test.placeholder.1");
        }
    }

    // free up memory for some reason ig lol (if we're switching scenes)
    public static void ClearCache()
    {
        cache.Clear();
        Resources.UnloadUnusedAssets();
    }
}
