using System.Collections.Generic;
using UnityEngine;

// generated by Google Gemini 3 Pro, checked by andy
// generic loader for anything in the resources folder
public static class ResourceManager
{
    // cache
    private static Dictionary<string, Object> cache = new Dictionary<string, Object>();

    /// <summary>
    /// Loads an asset of type T from the Resources folder.
    /// Usage: ResourceManager.Get<Sprite>("Art/UI/my_icon");
    /// Usage: ResourceManager.Get<AudioClip>("Audio/SFX/bonk");
    /// </summary>
    public static T Get<T>(string path) where T : Object
    {
        if (string.IsNullOrEmpty(path))
        {
            Debug.LogWarning("[ResourceManager] >> you passed an empty path");
            return null;
        }

        // check cache first
        if (cache.ContainsKey(path))
        {
            // found; cast to T and return
            var cachedAsset = cache[path] as T;
            if (cachedAsset != null) 
                return cachedAsset;
        }

        // load it from disk if not in cache
        T loadedAsset = Resources.Load<T>(path);

        if (loadedAsset != null)
        {
            // cache it for next time
            if (cache.ContainsKey(path)) cache[path] = loadedAsset;
            else cache.Add(path, loadedAsset);

            return loadedAsset;
        }
        else
        {
            // asset missing
            Debug.LogError($"[ResourceManager] >> can\'t find: '{path}' as type {typeof(T).Name}. returning null.");
            return null;
        }
    }

    // call this when switching scenes
    public static void ClearCache()
    {
        Debug.Log("[ResourceManager] >> cache cleared.");
        cache.Clear();
        Resources.UnloadUnusedAssets();
    }
}