using System.Collections.Generic;
using UnityEngine;

// generated by Google Gemini 3 Pro, checked by andy
// negative caching added by Claude Opus 5
// generic loader for anything in the resources folder
public static class ResourceManager
{
    // cache
    private static Dictionary<string, Object> cache = new();

    // paths we've already looked for and failed to find. without this, anything that asks for
    // a missing asset every frame (a ui icon, say) would hit the disk and log an error every
    // single frame. remembering the miss means we complain once and then shut up.
    private static HashSet<string> knownMisses = new();

    /// <summary>
    /// Loads an asset of type T from the Resources folder.
    /// Usage: ResourceManager.Get<Sprite>("Art/UI/my_icon");
    /// Usage: ResourceManager.Get<AudioClip>("Audio/SFX/bonk");
    ///
    /// Results are cached, hits and misses both. A path that's already come up empty returns
    /// null straight away without touching the disk or logging again, so it's safe to call
    /// this from Update or a per frame ui refresh.
    /// </summary>
    public static T Get<T>(string path) where T : Object
    {
        if (string.IsNullOrEmpty(path))
        {
            Debug.LogWarning("[ResourceManager] >> you passed an empty path");
            return null;
        }

        // check cache first
        if (cache.ContainsKey(path))
        {
            // found; cast to T and return
            var cachedAsset = cache[path] as T;
            if (cachedAsset != null)
                return cachedAsset;
        }

        // already looked for this one and it wasn't there
        if (knownMisses.Contains(path))
            return null;

        // load it from disk if not in cache
        T loadedAsset = Resources.Load<T>(path);

        if (loadedAsset != null)
        {
            // cache it for next time
            if (cache.ContainsKey(path)) cache[path] = loadedAsset;
            else cache.Add(path, loadedAsset);

            return loadedAsset;
        }
        else
        {
            // asset missing. remember that so we only say this once
            knownMisses.Add(path);
            Debug.LogError($"[ResourceManager] >> can\'t find: '{path}' as type {typeof(T).Name}. returning null.");
            return null;
        }
    }

    /// <summary>
    /// Checks whether a path has already been looked up and found missing.
    /// Lets callers pick a fallback without triggering another error log.
    /// </summary>
    public static bool IsKnownMiss(string path)
    {
        return !string.IsNullOrEmpty(path) && knownMisses.Contains(path);
    }

    /// <summary>
    /// Forgets every recorded miss so they get retried on the next <c>Get</c>.
    /// Only needed if assets can appear after the game's already looked for them.
    /// </summary>
    public static void ForgetMisses()
    {
        knownMisses.Clear();
    }

    /// <summary>
    /// Dumps everything and unloads whatever's no longer referenced.
    /// Call this when switching scenes.
    /// </summary>
    public static void ClearCache()
    {
        Debug.Log("[ResourceManager] >> cache cleared.");
        cache.Clear();
        knownMisses.Clear();
        Resources.UnloadUnusedAssets();
    }
}
