using UnityEngine;
using UnityEngine.Audio;


// generated by Google Gemini 3 Pro (running outta time to come up with shi myself lol)
// checked and revised by andy
public class AudioManager : MonoBehaviour
{
    public static AudioManager Instance;
    [SerializeField] AudioMixer mixer;

    // for playerprefs
    const string MASTER_KEY = "MasterVol";
    const string MUSIC_KEY = "MusicVol";
    const string SFX_KEY = "SFXVol";

    void Awake()
    {
        if (Instance == null) { Instance = this; DontDestroyOnLoad(gameObject); }
        else { Destroy(gameObject); }
    }

    void Start()
    {
        LoadVolume();
    }

    // hook these to ui sliders
    public void SetMasterVolume(float value)
    {
        mixer.SetFloat(MASTER_KEY, Mathf.Log10(value) * 20);
        PlayerPrefs.SetFloat(MASTER_KEY, value);
    }

    public void SetMusicVolume(float value)
    {
        mixer.SetFloat(MUSIC_KEY, Mathf.Log10(value) * 20);
        PlayerPrefs.SetFloat(MUSIC_KEY, value);
    }

    public void SetSFXVolume(float value)
    {
        mixer.SetFloat(SFX_KEY, Mathf.Log10(value) * 20);
        PlayerPrefs.SetFloat(SFX_KEY, value);
    }


    // loading stuff
    void LoadVolume()
    {
        float master = PlayerPrefs.GetFloat(MASTER_KEY, 1f);
        float music = PlayerPrefs.GetFloat(MUSIC_KEY, 1f);
        float sfx = PlayerPrefs.GetFloat(SFX_KEY, 1f);
        SetMasterVolume(master);
        SetMusicVolume(music);
        SetSFXVolume(sfx);
    }
}