using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Audio;
using DG.Tweening;

// generated by Google Gemini 3 Pro cuz there's no way we have time to write this ourselves lol
// checked by andy
public class AudioManager : MonoBehaviour
{
    public static AudioManager Instance;

    [Header("Mixer Stuff")]
    [SerializeField] AudioMixer mixer;
    // keys for playerprefs & mixer params
    const string MASTER_KEY = "MasterVol";
    const string MUSIC_KEY = "MusicVol";
    const string SFX_KEY = "SFXVol";

    [Header("Sources")]
    [SerializeField] AudioSource musicSourcePrimary;
    [SerializeField] AudioSource musicSourceSecondary;
    [SerializeField] AudioSource sfxSource;
    [SerializeField] AudioMixerGroup musicGroup; // assign these in inspector!
    [SerializeField] AudioMixerGroup sfxGroup;

    private Dictionary<string, SoundData> soundRegistry = new Dictionary<string, SoundData>();
    private bool isUsingPrimary = true;

    void Awake()
    {
        if (Instance != null && Instance != this) { Destroy(gameObject); return; }
        Instance = this;
        DontDestroyOnLoad(gameObject);

        InitializeRegistry();
    }

    void Start()
    {
        LoadVolume(); // Load saved volume settings on start
    }

    // ========================================================================
    // SETUP & REGISTRY
    // ========================================================================
    private void InitializeRegistry()
    {
        SoundData[] data = Resources.LoadAll<SoundData>("AudioData");
        foreach (var d in data)
        {
            if (!soundRegistry.ContainsKey(d.id)) soundRegistry.Add(d.id, d);
        }
    }

    // ========================================================================
    // SETTINGS MENU LOGIC (The Slider Stuff)
    // ========================================================================
    public void SetMasterVolume(float value)
    {
        mixer.SetFloat(MASTER_KEY, Mathf.Log10(value) * 20);
        PlayerPrefs.SetFloat(MASTER_KEY, value);
    }

    public void SetMusicVolume(float value)
    {
        mixer.SetFloat(MUSIC_KEY, Mathf.Log10(value) * 20);
        PlayerPrefs.SetFloat(MUSIC_KEY, value);
    }

    public void SetSFXVolume(float value)
    {
        mixer.SetFloat(SFX_KEY, Mathf.Log10(value) * 20);
        PlayerPrefs.SetFloat(SFX_KEY, value);
    }

    private void LoadVolume()
    {
        SetMasterVolume(PlayerPrefs.GetFloat(MASTER_KEY, 1f));
        SetMusicVolume(PlayerPrefs.GetFloat(MUSIC_KEY, 1f));
        SetSFXVolume(PlayerPrefs.GetFloat(SFX_KEY, 1f));
    }

    // ========================================================================
    // PLAYBACK LOGIC (The Universal Player Stuff)
    // ========================================================================
    public void PlaySFX(string id)
    {
        if (TryGetSound(id, out SoundData data))
        {
            sfxSource.pitch = data.pitch;
            sfxSource.PlayOneShot(data.mainClip, data.volume);
        }
    }

    public void PlayMusic(string id, float fadeDuration = 1f)
    {
        if (!TryGetSound(id, out SoundData data)) return;

        AudioSource activeSource = isUsingPrimary ? musicSourcePrimary : musicSourceSecondary;
        AudioSource newSource = isUsingPrimary ? musicSourceSecondary : musicSourcePrimary;

        newSource.Stop();
        newSource.clip = data.mainClip;
        newSource.volume = 0;
        newSource.pitch = data.pitch;
        newSource.loop = data.loop;
        newSource.outputAudioMixerGroup = musicGroup; // ensure routing

        if (data.introClip != null)
        {
            newSource.loop = false;
            newSource.clip = data.introClip;
            newSource.Play();
            StartCoroutine(WaitForIntroThenLoop(newSource, data));
        }
        else
        {
            newSource.Play();
        }

        activeSource.DOFade(0, fadeDuration).OnComplete(() => activeSource.Stop());
        newSource.DOFade(data.volume, fadeDuration);

        isUsingPrimary = !isUsingPrimary;
    }

    public void StopMusic(float fadeDuration = 1f)
    {
        musicSourcePrimary.DOFade(0, fadeDuration).OnComplete(() => musicSourcePrimary.Stop());
        musicSourceSecondary.DOFade(0, fadeDuration).OnComplete(() => musicSourceSecondary.Stop());
    }

    public List<SoundData> GetAllRegisteredSounds() => new List<SoundData>(soundRegistry.Values);

    private bool TryGetSound(string id, out SoundData data)
    {
        if (string.IsNullOrEmpty(id) || !soundRegistry.TryGetValue(id, out data))
        {
            data = null;
            return false;
        }
        return true;
    }

    private IEnumerator WaitForIntroThenLoop(AudioSource source, SoundData data)
    {
        yield return new WaitForSecondsRealtime(data.introClip.length - 0.05f);
        source.clip = data.mainClip;
        source.loop = true;
        source.Play();
    }
}