using TMPro;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.UI;

// generated by Google Gemini 3 Pro
// checked and revised by andy
public class RebindButton : MonoBehaviour
{
    [Header("Setup")]
    // Drag the Action from the list here (e.g. "Battle/Confirm")
    [SerializeField] InputActionReference actionToRebind;
    [SerializeField] TextMeshProUGUI buttonText;
    [SerializeField] Button button;

    private InputAction actionInstance; // the actual action we are modifying
    private InputActionRebindingExtensions.RebindingOperation rebindOperation;

    void Start()
    {
        // 1. Find the REAL action living in MenuManager
        // (we look it up by name to ensure we edit the persistent one)
        var controls = MenuManager.Instance.gameControls;
        actionInstance = controls.asset.FindAction(actionToRebind.action.id);

        // 2. Refresh visual immediately
        UpdateDisplay();

        // 3. Auto-hook up the button click
        button.onClick.AddListener(StartRebinding);
    }

    void StartRebinding()
    {
        // Visual feedback
        buttonText.text = "...";
        button.interactable = false; // prevent spam clicking

        // Disable action while rebinding to avoid weird side effects
        actionInstance.Disable();

        // THE MAGIC PART
        rebindOperation = actionInstance.PerformInteractiveRebinding()
            .WithControlsExcluding("Mouse") // <--- This bans mouse inputs!
            .OnMatchWaitForAnother(0.1f)    // small delay to prevent accidental instant binds
            .OnComplete(operation => RebindComplete())
            .Start();
    }

    void RebindComplete()
    {
        // cleanup
        rebindOperation.Dispose();
        actionInstance.Enable();
        button.interactable = true;

        // update visual
        UpdateDisplay();

        // SAVE IT
        MenuManager.Instance.SaveUserRebinds(MenuManager.Instance.gameControls);
    }

    void UpdateDisplay()
    {
        // gets the readable name of the key (e.g. "Space" or "E")
        int bindingIndex = actionInstance.GetBindingIndexForControl(actionInstance.controls[0]);
        buttonText.text = InputControlPath.ToHumanReadableString(
            actionInstance.bindings[0].effectivePath,
            InputControlPath.HumanReadableStringOptions.OmitDevice
        );
    }
}