using UnityEngine;
using UnityEngine.InputSystem;

// generated by Google Gemini 3 Pro
// checked and revised by andy
public class RebindButton : MonoBehaviour
{
    public InputActionReference actionRef; // drag in reference
    public TMPro.TextMeshProUGUI bindingText;
    public GameObject waitingForInputOverlay; // toggled when rebinding

    public void StartRebinding()
    {
        waitingForInputOverlay.SetActive(true);

        actionRef.action.PerformInteractiveRebinding()
            .WithControlsExcluding("Mouse") // dont want mouse bindings
            .OnMatchWaitForAnother(0.1f)
            .OnComplete(operation => RebindComplete(operation))
            .Start();
    }

    void RebindComplete(InputActionRebindingExtensions.RebindingOperation op)
    {
        op.Dispose();
        waitingForInputOverlay.SetActive(false);
        bindingText.text = actionRef.action.GetBindingDisplayString(0);

        MenuManager.Instance.SaveUserRebinds(MenuManager.Instance.gameControls);
    }
}