using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;

// generated by google gemini 3 pro
// im too lazy to write this thing sry
// checked by andy

// basically it scrolls a scrolling thing when it makes sense. that's it. apparently unity doesn't have this
// as a default supported feature which is actually fkin stupid
public class ScrollZone : MonoBehaviour
{
    public ScrollRect scrollRect;
    public float scrollSpeed = 500f;
    public float triggerMargin = 40f; // how close to edge b4 it starts scrolling

    RectTransform viewport;
    RectTransform content;

    void Start()
    {
        if (!scrollRect) scrollRect = GetComponent<ScrollRect>();
        viewport = scrollRect.viewport;
        content = scrollRect.content;
    }

    void LateUpdate()
    {
        GameObject selected = EventSystem.current.currentSelectedGameObject;

        // basic checks to make sure we actually selected something in the list
        if (selected == null || !selected.transform.IsChildOf(content)) return;

        // magic function: ignore all the world space complexity
        // this gives us the selected item's position AS IF it were a child of the viewport
        Vector3 itemLocalPos = viewport.InverseTransformPoint(selected.transform.position);

        // viewport pivot in your scene is (0, 1) aka Top-Left
        // so Top is Y=0, Bottom is Y = -height
        float viewportHeight = viewport.rect.height;
        float topBoundary = 0 - triggerMargin;
        float bottomBoundary = -viewportHeight + triggerMargin;

        // check if we are too high (near top edge)
        if (itemLocalPos.y > topBoundary)
        {
            // move content down (decrease Y) to show top stuff
            content.anchoredPosition -= new Vector2(0, scrollSpeed * Time.deltaTime);
        }
        // check if we are too low (near bottom edge)
        else if (itemLocalPos.y < bottomBoundary)
        {
            // move content up (increase Y) to show bottom stuff
            content.anchoredPosition += new Vector2(0, scrollSpeed * Time.deltaTime);
        }
    }
}